edition = "2024"
newline_style = "Unix"
use_field_init_shorthand = true

unstable_features = true
group_imports = "StdExternalCrate"
comment_width = 100
wrap_comments = true
format_code_in_doc_comments = true
imports_granularity = "Crate"
format_strings = true
reorder_impl_items = true

error_on_line_overflow = true
